server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: interview-guide

logging:
  level:
    com.interview: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always 